SELECT FULL_NAME, ECI FROM temp_EMP_INFO WHERE ECI IN
  (SELECT ECI FROM temp_EMP_INFO GROUP BY ECI HAVING COUNT(*) > 1) ORDER BY ECI
  
SELECT t1.ROWID,t1.FULL_NAME, t1.ECI
FROM temp_EMP_INFO t1
LEFT JOIN SCOPE_EMP t2 ON t2.FULL_NAME = t1.FULL_NAME
WHERE t2.FULL_NAME IS NULL

SELECT t1.ROWID,t1.FULL_NAME, t1.ECI
FROM EMP_INFO t1
LEFT JOIN SCOPE_EMP t2 ON t2.FULL_NAME = t1.FULL_NAME
WHERE t2.FULL_NAME IS NULL
  